import Head from "next/head";

// local imports
import Navbar from "../components/Navbar";
import Feed from "../components/Feed";

// NextAuth imports
import { signIn, useSession } from "next-auth/react";
import Login from "./login";

export default function Home() {
  const { data: session } = useSession();

  // if (!session) return <Login />;

  return (
    <div>
      <Head>
        <title>Techie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Feed />
      </main>
    </div>
  );
}
